Changed Lobatto Integration to variable order version
nutofem/nuto pull request #69
Opened 2017-06-28 07:22 UTC by pmueller2

IntegrationType Lobatto takes number of integration points as parameter in the constructor.
Lobatto weights and nodes are calculated instead of looking them up.

The enums are still there, which maybe should be changed also, if this is a useful addition.

Similar changes could be made to Gauss integration.

Is this useful? What do you think?

2017-06-28 08:27 UTC, TTitscher requested changes
I like this change very much. Increase functionality while reducing the code massively. Please work on the code style changes I suggested. 

One more idea: Can we make it more static? A template parameter <TDegree>? With the recent changes in the language and c++14 constexpr, can we even make the calculations constexpr?

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +double NuTo::Math::Polynomial::legendre_p_deriv(int n, double x, int k) {
Please stick to our code style - method names in CamelCase.

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +#include <math.h>
#include <cmath> instead. <math.h> is the c version
https://stackoverflow.com/questions/15656434/include-cmath-vs-include-math-h-in-a-c-program

math.h defines methods globally, and cmath in the namespace `std`. So you'll have to modify the math methods

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +#include <stdlib.h>
c header, remove that

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +    if (n < k) {
Again code style, opening and closing brackets in a new line. Run clang-format on your code, there is a tutorial in our documentation https://github.com/nutofem/nuto/blob/master/doc/dev/CodingStyle.md

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +        for (int i=1; i<= (2*k);i++) {
Please implement a generic factorial function (including a simple test) to make the code more expressive.
Same goes for the power function. You could use std::pow (only defined for floating point types) or move this code into a helper function

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +            pow2_k *= 2;
why is fac_k, fac_2k and pow2_k not an integer type?

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +        do
You implement the newton algorithm twice.

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.h
> +    static double legendre_p_deriv(int n, double x , int k);
Please add proper doxygen documentation. What is x?

2017-06-28 08:27 UTC, TTitscher commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.cpp
> +//! @brief returns the weight of an integration point
Remove doxygen comments in the cpp files.

2017-06-28 08:27 UTC, TTitscher commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.h
> +#ifndef IntegrationType1D2NLobatto_H
#pragma once is our style

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +    } else if (n==k) {
I personally like to keep the code as flat as possible. If your `if` block returns something, you can continue without an `else`. In general, this would have been much shorter and more readable:
~~~cpp
if (n < k)
   return 0;
if (n == k)
   return Factorial(2*k) / (Power(2, k) * Factorial(k));
return ( ( (2.*n-1.)*x* legendre_p_deriv(n-1,x, k) - (n-1.+k) * legendre_p_deriv(n-2,x, k) )/(n-k)
~~~

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +    std::vector<double> x;
it is generally good practice to allocate memory in the `std::vector` at once, whenever it is possible. Now, the push_back resizes the vector multiple times. (In this case, performance does not matter, but still, good practice...). You can either call a x.reserve(n) or the ctor vector<double> x(n).

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +    for(int i=0; i<n; i++)
I suggest renaming the vector x to xs or some other kind of plural term. Then use a range based for loop
~~~cpp
for (double x : xs)
~~~
instead of x[i] all over the place.

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +    double tol = 1e-8;
Why 1e-8? Is that enough?

2017-06-28 08:27 UTC, TTitscher commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.cpp
> +        weights.push_back(2./(nIps*(nIps-1)) );
You can resize/reserve weights before pushing into it.

2017-06-28 08:27 UTC, TTitscher commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.cpp
> +    else
Personally, i would delete the else since the corresponding if returns.

2017-06-28 08:27 UTC, TTitscher commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.h
> +    std::vector<double> weights;
Code style. All members should start with `m`.

2017-06-28 08:27 UTC, TTitscher commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.h
> +    int nIps;
Maybe we could remove this member and return the size of on of the other members instead.

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.cpp
> +#include "boost/math/special_functions/legendre.hpp"
You do not need this include, right?

2017-06-28 08:27 UTC, TTitscher commented on src/math/Polynomial.h
> +class Polynomial
IMO the name `Polynomial` is misleading, it's more like `Legendre`, right?

And please provide a unit test, e.g. a comparison to wikipedia values of the gauss-lobatto points.

2017-06-28 08:27 UTC, TTitscher commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.cpp
> +            weights.push_back(2./(nIps*(nIps-1))/( lp * lp) );
You can think about moving this code to `Polynomial` as well.

2017-06-28 08:27 UTC, TTitscher commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.cpp
> +    iPts.push_back(1.);
You can simplify this code a lot by inserting the `(-1)` at the front of the vector.
~~~cpp
nIps = NuTo::Math::Polynomial::legendre_deriv_roots(numIps-1);
nIps.insert(nIps.begin(),-1.);
nIps.push_back(1.);
~~~

2017-06-28 09:12 UTC, Psirus requested changes
I think that's a good idea. Just to add to the things that @TTitscher has already mentioned: please add unit tests for the Polynomial and the IntegrationType.

2017-06-28 09:12 UTC, Psirus commented on src/math/Polynomial.h
> +class Polynomial
This class has no members and only static functions. [It should be a namespace with free functions instead](https://stackoverflow.com/questions/1434937/namespace-functions-versus-static-methods-on-a-class).

2017-06-28 09:12 UTC, Psirus commented on src/mechanics/integrationtypes/IntegrationType1D2NLobatto.cpp
> +NuTo::IntegrationType1D2NLobatto::IntegrationType1D2NLobatto(int numIps)
Use direct initialization for `nIps`, i.e `IntegrationType1D2NLobatto(int numIps) : nIps(numIps) { ... }` and then just use `nIps` throughout the constructor.

2017-06-28 17:11 UTC, Psirus approved these changes
Nicely done!

2017-06-28 17:11 UTC, Psirus commented on test/math/CMakeLists.txt
> +        math/Polynomial.cpp
This should be redundant. The `add_unit_test` macro should automatically add the corresponding cpp file.

2017-06-28 17:11 UTC, Psirus commented on test/math/Polynomial.cpp
> +    for (int i=0; i<order; i++) {
You can use `BoostUnitTest::CheckVector` instead of this for loop.

2017-06-29 12:10 UTC, TTitscher commented on test/math/Polynomial.cpp
> +    for (int i=0; i<order; i++) {
This is a problem with values very close to zero, since BOOST_CHECK_CLOSE calculates the relative error, possibly dividing by zero

2017-06-29 13:29 UTC, TTitscher approved these changes

2017-06-29 14:39 UTC, potto1 commented
In the IGA branch the Gauss integration class with variable number of IPs is impelemnted as template. I think we have to agree in the question, whether use templates or argument in the constructor.

2017-06-30 07:44 UTC, TTitscher commented
One more remark: Can we think about renaming `Polynomial.h/cpp` to `Legendre.h/cpp`? Its functions can stay in the `namespace Polynomial`. Imagine adding other types of polynomials, whatever that might be. But they can go in a separate `h/cpp` file, also in the `namespace Polynomial`.

2017-06-30 08:32 UTC, Psirus commented
1. Unless we manage something `constexpr` where the computation is done at compile time, I'd say we use a "normal" parameter. Nothing gained by using templates except rigidity / no proper python support.
2. Yes, let's rename it to Legendre.

2017-07-03 09:19 UTC, TTitscher commented
Nice work with the Gauss integration as well! Is there a way to generate these points for higher dimensions as well? I can imagine that 2DQuad and 3DBrick are tensor products of the underlying 1D type. How does it work for Triangle/Tetrahedron?

2017-07-03 10:28 UTC, merged