Integration tensor product
nutofem/nuto pull request #78
Opened 2017-07-11 07:18 UTC by pmueller2

The integration types for
1D Line Gauss/Lobatto
2D Quad Gauss/Lobatto
3D Brick Gauss/Lobatto
are now unified and have variable order.
The enums are still the same. If you want to create an integration type with an order that has no enum you have to instantiate it yourself (not through the structure).

2017-07-11 10:57 UTC, Psirus requested changes
I like this, a lot of code duplication removed. The `IntegrationTest` should become a unit test and really test something.

Also, we should start thinking about how to get rid of the enum, because it is really not sensible anymore.

2017-07-11 10:57 UTC, Psirus commented on applications/integrationtests/mechanics/IntegrationTest.cpp
> +                  << "Result: " << integrate3D(polyOrder, *(intType)) << std::endl;
I second the motion for an actual test, rather than just printing the results. Also, this test should be splitted into unittests.

2017-07-11 10:57 UTC, Psirus commented on applications/integrationtests/mechanics/uniaxial/ElementUniaxial3D.cpp
> +//}
Why are all of these commented out?

2017-07-11 10:57 UTC, Psirus commented on src/mechanics/constitutive/laws/LinearElasticInhomogeneous.h
> +class LinearElasticInhomogeneous: public LinearElasticEngineeringStress
...what has this got to do with `IntegrationType`s?

2017-07-11 10:57 UTC, Psirus commented on src/mechanics/integrationtypes/IntegrationTypeTensorProduct.cpp
> +NuTo::IntegrationTypeTensorProduct<TDim>::IntegrationTypeTensorProduct(size_t nIps,
Make this an `int` rather than an unsigned type, because the implicit conversion will cause weird bugs ("no unsigned in interfaces").

2017-07-11 10:57 UTC, Psirus commented on src/mechanics/integrationtypes/IntegrationTypeTensorProduct.cpp
> +        ComputeWeightsAndPoints1DLobatto(nIps, weights, mIPts1D);
These should return the `weigths` and `mIPts1d` rather than taking references.

2017-07-11 10:57 UTC, Psirus commented on src/mechanics/integrationtypes/IntegrationTypeTensorProduct.cpp
> +                "[NuTo::IntegrationTypeTensorProduct::GetLocalIntegrationPointCoordinates] Ip number out of range.");
Use `__PRETTY_FUNCTION__` instead of manually typing the name of the function again.

2017-07-11 10:57 UTC, Psirus commented on src/mechanics/integrationtypes/IntegrationTypeTensorProduct.cpp
> +        std::cout << std::endl;
Not needed?! Maybe a leftover from `cout`-debugging?

2017-07-11 10:57 UTC, Psirus commented on src/mechanics/integrationtypes/IntegrationTypeTensorProduct.cpp
> +                std::cout << std::endl;
Ditto.

2017-07-12 06:54 UTC, pmueller2 commented on src/mechanics/constitutive/laws/LinearElasticInhomogeneous.h
> +class LinearElasticInhomogeneous: public LinearElasticEngineeringStress
Nothing. I think it is still useful. Will move it to a seperate commit on master.

2017-07-12 06:54 UTC, pmueller2 commented on applications/integrationtests/mechanics/uniaxial/ElementUniaxial3D.cpp
> +//}
my mistake (leftovers from testing)

2017-07-12 07:51 UTC, Psirus commented on src/mechanics/constitutive/laws/LinearElasticInhomogeneous.h
> +class LinearElasticInhomogeneous: public LinearElasticEngineeringStress
Sorry, that came out wrong. I was just wondering; It could've stayed in here.

2017-07-21 11:10 UTC, Psirus approved these changes

2017-07-21 13:32 UTC, closed without merging